name: Shedule Task

on:
  schedule:
      - cron: "0 0 * * *"

jobs:
    task:
      runs-on: ubuntu-latest
      steps:
      - name: step1
        run: |
          date
          pwd
          ls -lah
          free -h
          cat /proc/cpuinfo